import { /* inject, */ BindingScope, injectable} from '@loopback/core';
var cloudinary = require('cloudinary');
const DATA_PATH = "../data/db.json"

cloudinary.config({
  cloud_name: 'planner-storage',
  api_key: '217698628168953',
  api_secret: 'azP1tqca9AGCamLa6TMXbOan4n0',
  secure: false
});

@injectable({scope: BindingScope.TRANSIENT})
export class DataBackupService {
  constructor(/* Add @inject to inject parameters */) { }

  /*
   * Add service methods here
   */


  run() {
    this.uploadData()
  }

  uploadData() {

    cloudinary.v2.uploader.upload(DATA_PATH, {resource_type: "raw"}).then(function (textFile: any) {
      console.log();
      console.log("** File Upload (Promise)");
      console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
      console.log("* " + textFile.public_id);
      console.log("* " + textFile.url);
    })
      .catch(function (err: any) {
        console.log();
        console.log("** File Upload (Promise)");
        if (err) {console.warn(err);}
      });

  }
}
